### ISSUE TITLE
how to install and use this theme

### ISSUE THREAD

**Issue by navotera** [damyon/moodle-theme_photo#2]
im very sorry, im new in moodle theme customization. i need to extend the default moodle to my custom design so i have to try this theme as simulation and example. but i got one problem. 

how to use this theme i already copy-paste this theme folder to the **moodle/themes** but when i access : 

    Dashboard
    Site administration
    Appearance
    Themes
    Theme selector

this theme is not appear.

**Comment by michaelmeneses** [comment]
Hello @navotera,

Check if the folder MOODLE/theme/photo exists.
Go to http://MOODLE/admin/index.php and check if the theme is requested to install.

Michael Meneses

**Comment by navotera** [comment]
good it works now, previously i copas the folder named master-photo from github. thanks u.
